name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        sudo sysctl kernel.perf_event_paranoid=-1
        sudo sysctl kernel.kptr_restrict=0
        make
